Dev
houseofgeeks/tap pull request #15
Opened 2021-12-29 13:24 UTC by EricLiclair

### Fixes #<number>
<Do not delete this template>
Description: <provide a description> The title should be short and relevant.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [ ] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
<provide a relevant screenshot or any testimonial for the solved issue if applicable>

Initial home
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/65639964/147665927-3b5806e8-5995-43fa-b90f-a15cbd6a337f.png">

Folder structure
<img width="79" alt="image" src="https://user-images.githubusercontent.com/65639964/147665987-2bfa85b6-a6c0-452c-8453-097ede404c03.png">

Ignorable warning for Lottie file: will be removed once development starts.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/65639964/147666466-bcec16d0-f65e-45fc-a768-76d8d5968ca2.png">

2021-12-29 14:34 UTC, EmperorYP7 requested changes
Commit the `/client/yarn.lock` file as well

2021-12-29 14:34 UTC, EmperorYP7 commented on client/.gitignore
> +/node_modules
this file should be deleted

2021-12-30 05:09 UTC, SrijanSriv commented
@EricLiclair while you're at it with the folder restructuring, sort the multiple `Code_of_Conduct.md` thing as well. Also, theming includes only mui right?

2021-12-30 06:58 UTC, EmperorYP7 approved these changes
LGTM

2021-12-30 06:59 UTC, merged

2021-12-30 07:50 UTC, EricLiclair commented
Hey, @EmperorYP7 thanks for the changes. Also, @SrijanSriv Yes. Theming is purely done using themprovider @mui . Thought of adding framer but i believe that can be added when implementing animations.