footer responsiveness fixed
houseofgeeks/tap pull request #23
Opened 2022-01-11 07:53 UTC by abhishekrathi16

### Fixes #<number>

Description: The footer designed earlier by me had problems for responsiveness and the code was breaking down when paired with the navbar. This pull request has code which uses mui-grids as well as react props and mapping and ensures that the code doesn't break down in different screen sizes. Complements the navbar design.

#### Checklist
- [x] I've followed the Contributing guidelines provided in the repository.
- [x] I've made the changes which were demanded in the linked issue.
- [x] I've tested my code on a Chromium based browser.
- [x] I've tested my code on Mozilla Firefox.
- [x] My code gave a clean console on debugging. (no warnings/errors)

#### Testimonial
![ss1](https://user-images.githubusercontent.com/82315852/148902400-d069759e-8e42-4ecc-bd02-57cda22f41cd.png)
![ss2](https://user-images.githubusercontent.com/82315852/148902416-7e5a2bc5-44d3-427b-859c-2ec8e23986ab.png)
![ss3](https://user-images.githubusercontent.com/82315852/148902434-8532f33f-e47c-4975-9589-13df43b9ac95.png)

2022-01-11 11:45 UTC, abhishekrathi16 commented
Still need to add some proper sizing to the icons before it's good to go.

2022-01-11 18:09 UTC, EmperorYP7 requested changes

2022-01-11 18:09 UTC, EmperorYP7 commented on client/components/footer/Data.js
> +        line1: "B.Tech Course",
Why not make this an array?
```suggestion
        "quick_access": [
            {
                "line": "B.Tech Course",
                "link": ""
            },
            // .. and so on
        ],
```

2022-01-11 18:09 UTC, EmperorYP7 commented on client/components/footer/Data.js
> +        line1: "Youtube Channel",
This as well.
```suggestion
        "student_corner": [
            {
                "line": "B.Tech Course",
                "link": ""
            },
            // .. and so on
        ],
```

2022-01-11 18:09 UTC, EmperorYP7 commented on client/components/footer/Data.js
> +        line1: "tap@iiitranchi.ac.in",
Here as well

2022-01-11 18:09 UTC, EmperorYP7 commented on client/components/footer/Group.js
> +      <Grid
Sweet!

2022-01-12 13:04 UTC, abhishekrathi16 commented
The changes requested will not change the footer significantly although changing the data arrangement that I am passing as props will need me to change a lot in the code, perhaps the mapping and props as well as styling. Please re-consider the changes requested and if you still feel the need to change the code I'll do it without any issues. Also, update me about the footer design that you want for mobile view, I will update the code accordingly.

2022-01-13 06:39 UTC, EmperorYP7 requested changes
The output looks good to me. However, consider the case where we want to customize the fields in the footer; we'd need to restructure `Data.js` so that just by adding and removing elements from the list, we can produce correct results. So, better be it now.

2022-01-13 06:53 UTC, abhishekrathi16 commented
Okay, then I'll start working on it right away.
And do you want me to fix the mobile view as discussed in the group?

2022-01-13 06:58 UTC, EmperorYP7 commented
> And do you want me to fix the mobile view as discussed in the group?

Yes.

2022-01-23 16:25 UTC, abhishekrathi16 commented
The requested changes have been made, please review the changes and inform me if there is anything you would want me to do.
@EmperorYP7

2022-01-25 08:09 UTC, EmperorYP7 approved these changes
LGTM! well done.

2022-01-25 08:09 UTC, merged