Docs
houseofgeeks/tap pull request #9
Opened 2021-12-26 13:39 UTC by utkarsh0908

Added Docs for the project.
Kindly check the Getting Started part

2021-12-26 14:22 UTC, EmperorYP7 requested changes
Just a few tweaks and we're good to go!

2021-12-26 14:22 UTC, EmperorYP7 commented on README.md
> +# House of Geeks - Official Technical Communtiy of IIITR
```suggestion
# Training and Placement Cell, IIIT Ranchi Web App
```

2021-12-26 18:06 UTC, EmperorYP7 approved these changes
LGTM

2021-12-26 18:07 UTC, merged

2021-12-27 02:36 UTC, utkarsh0908 commented
> Just a few tweaks and we're good to go!

Looking good to me.